### PR TITLE
allow binary in `bin` directory

### PR DESCRIPTION
**Pull request by garak**
(also remove `2` from `Symfony2`, since it doesn't make much sense anymore)

### CODE REVIEW

**Comment by Jean85** [comment]
Thanks for the contribution! 

Why would you prefer the `bin` directory, instead of leaving it not specified, and using the standard `vendor/bin`?
Also, test are failing here, the Travis build should be changed.

**Comment by garak** [comment]
Well, `bin` directory is as much standard as `vendor/bin`, but shorter :wink:

**Comment by ranpafin** [comment]
@garak Usually it's up to the master *composer.json* to specify a script (bin) directory. Would this change force the creation of the directory **bin/** in the host project?

**Comment by Jean85** [comment]
Yeah @garak it's shorter, but I've already included a much faster shortcut in the Docker dev environment: https://github.com/facile-it/paraunit/commit/484d7ca81481028ca96c0b274dba0c93aa36489a#diff-75b956b60058d9d79f9c460a207916daR52

The `vendor/bin` folder in already in the `$PATH` environment variable, so no folder is needed to run any binary when developing this project.

**Comment by garak** [comment]
@ranpafin it's not forcing anything outside this project
@Jean85 you could change that to `./bin` (that's what I'm using for my local dev machine)

**Comment by ranpafin** [comment]
@garak very well, then. If you could change the .zsh config file as well then :+1: 
@Jean85 Even the project hold only a single binary i see no reason to not keep the binary invocation shorter.

**Comment by Jean85** [comment]
Fine, LGTM now!
Thanks @garak

**Pull request merged**
