### PR TITLE
new dockerfile and build script for 5.6 and 7

### PR DESCRIPTION
**Pull request by ranpafin**
Opening the PR for review.

Mostly some cleanup work but now we'll be able to run tests inside the php-7 container and the php-5.6 one.

I've kept the original Dockerfile separated for now but it should be declared deprecated and maybe removed in the next release.

I've removed xdebug and the segfault extension from the php-7 container as for now they don't apply.

### CODE REVIEW

**Comment by Jean85** [comment]
Good work! How long does it take to build? It's faster than the older image?
Why did you remove the sigsev from PHP7? Segfault can still happen in PHP7 too, they are just harder to come by...

As for xDebug, it's ok to remove it for now, probably I will add it later, together with PHPDbg, for the coverage feature.

Umh, I would have liked a 5.3 container (I always commit something that breaks under 5.3! :P) but I see that it isn't available... Travis will save us!

**Comment by ranpafin** [comment]
@Jean85 The image it's way faster to build!

I've removed the segfault extension as i assumed it would work only for PHP <=5.6. Instead it works quite allright. see commit [ ffe96cd ](https://github.com/facile-it/paraunit/pull/43/commits/ffe96cde3bfe5d43e642d10324be0edc97e71779)

As for 5.3 i think it can be arranged but it will require a bit of work. The main problem would be to compile xdebug from source as the pecl installation require >=5.4.

**Comment by Jean85** [comment]
Don't worry about 5.3, it's a minimal issue. I've configured my IDE to use 5.3 syntax, and we have Travis anyway.

**Comment by Jean85** [comment]
Also: the `start.sh` file is still relevant?

**Comment by ranpafin** [comment]
I'm not using it anymore as I mostly relay on the **setup.sh** script. 
The goal of the **start*.sh* script should be to give a fast shell access without the need of rebuild the whole container.
I'd say let's leave it there until the old *Dockerfile* lives I wouldn't add a **start.sh** script for the two new containers.

**Comment by ranpafin** [comment]
@Jean85 about Xdebug and the coverage  the new 2.4 version it should be compatible with PHP7.

There are still some issue like [issue](https://github.com/sebastianbergmann/php-code-coverage/issues/422) and  [issue](https://github.com/sebastianbergmann/php-code-coverage/issues/411) but it looks promising

**Comment by Jean85** [comment]
The xDebug support for PHP7 is not my concern; also, PHPDbg seems to be faster for coverage collection, so I would prefer it if available: Paraunit is about performances and faster execution after all!

LGTM :+1:  for this PR, anyway!

**Comment by Jean85** [comment]
Thanks @ranpafin!

**Pull request merged**
