### PR TITLE
feat: allow PHPUnit 11 (WIP)

### PR DESCRIPTION
**Pull request by Chris53897**
`composer require "phpunit/phpunit:11.0.1" --dry-run``

```
  Problem 1
    - Root composer.json requires phpunit/phpunit 11.0.1 (exact version match: 11.0.1 or 11.0.1.0), found phpunit/phpunit[11.0.1] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - phpspec/prophecy-phpunit is locked to version dev-master and an update of this package was not requested.
    - phpspec/prophecy-phpunit dev-master requires phpunit/phpunit ^9.1 || ^10.1 -> found phpunit/phpunit[9.1.0, ..., 9.6.16, 10.1.0, ..., 10.5.10] but it conflicts with your root composer.json require (11.0.1).
```

### CODE REVIEW

**Review by Jean85 — CHANGES_REQUESTED** [review]
This is unfortunately not enough, since Prophecy is stopping the upgrade too.

We need two additional, external PRs for that, one in `phpspec/prophecy-phpunit` (to allow PHPUnit 11), the second in `phpspec/prophecy` (to allow `sebastian/comparator` 6).

I'll try to do that ASAP, but I starting to think that I may migrate toward PHPUnit's mocks...

**Comment by Chris53897** [comment]
I did a look at this repos, and there is maybe more :(
I am not sure if there are circular dependencies between "phpspec/prophecy" and  "phpspec/phpspec".
That was the point i decided that this does not need to be solved today ;)

**Comment by kubawerlos** [comment]
> I starting to think that I may migrate toward PHPUnit's mocks...

If you make this decision I'd be happy to help. I already did it in PHP CS Fixer repo.

**Comment by Jean85** [comment]
Ok, I've filed https://github.com/phpspec/prophecy/pull/616 and https://github.com/phpspec/prophecy-phpunit/pull/59, but we need both of them to work here. I'll try to commit the requirement for https://github.com/phpspec/prophecy-phpunit/pull/58 to pull this off.

> If you make this decision I'd be happy to help. I already did it in PHP CS Fixer repo.

Thanks! That would be helpful: the only doubt that I have is that in that way, I would be bound to PHPUnit breaking changes, and I do not know if that would be better or worse compared to the issues I'm having with Prophecy.

**Comment by Jean85** [comment]
Closing in favor of #230, GitHub Actions are not allowing secrets to be used when the PR comes from a fork.

**Pull request closed without merging**
