### PR TITLE
feat: allow PHPUnit 11

### LINKED ISSUE #226: Support for PHPUnit 11
https://packagist.org/packages/phpunit/phpunit was released today.

I did a quick PR just to test if there are any changes nedded.
There are only some. But i do not know how to fix it.

### PR DESCRIPTION
**Pull request by Chris53897**
https://github.com/facile-it/paraunit/issues/226

### CODE REVIEW

**Comment by Jean85** [comment]
PHPUnit 11 does not support PHP 8.1, but you still have failure there too: https://github.com/facile-it/paraunit/actions/runs/7754078301/job/21146669794?pr=225#step:6:11

I suspect the build is broken on the main branch too.

**Comment by Chris53897** [comment]
Thanks for working on this
https://github.com/facile-it/paraunit/pull/227

**Comment by Jean85** [comment]
Wow, incredible! After making the base build green with #227, it works flawlessly without any change!

I'll add a changelog entry and release it!

**Comment by Chris53897** [comment]
perfect, thanks

**Comment by kubawerlos** [comment]
> it works flawlessly without any change!

@Jean85 that's because PHPUnit was not allowed after all.

PHPUnit 11 requires `phpunit/php-code-coverage:^11.0`: https://github.com/sebastianbergmann/phpunit/blob/11.0.0/composer.json#L35

Which is not allowed:
https://github.com/facile-it/paraunit/blob/2.3.0/composer.json#L30

**Comment by Jean85** [comment]
Aw crap, my fault! I didn't check that 11 was effectively running...

**Comment by kubawerlos** [comment]
I'm on it: https://github.com/facile-it/paraunit/pull/228

**Comment by Jean85** [comment]
Watch out, there's #229 too, and I've already posted a comment there.

**Pull request merged**
