### PR TITLE
Add support to PostgreSQL deadlock

### PR DESCRIPTION
**Pull request by elernonelma**
An example of output can be found at https://github.com/lib/pq/issues/486#issuecomment-242049302

### CODE REVIEW

**Comment by elernonelma** [comment]
phpstan checks fails running at php7.4 - I only got a php7.3 instance running here so I don't know what's going on exactly.

**Comment by Jean85** [comment]
Thanks for the contribution! Code looks fine to me, I'm triggering a new build on master to check if the issue is not related to your PR: https://travis-ci.com/github/facile-it/paraunit/builds/164140752

**Comment by Jean85** [comment]
Build should be fixed in f8ebf30, restarting your build to see if it's green.

**Comment by elernonelma** [comment]
Seems greet thanks for the hotfix!

**Pull request merged**
