### PR TITLE
[WIP] Advanced PhpUnit compatibility check

### PR DESCRIPTION
**Pull request by sergeyz**

### CODE REVIEW

**Comment by Jean85** [comment]
Thanks for the contribution!

Why are you adding all those version tests? PHPUnit follows semantic versioning, so a minor version shouldn't break the compatibility. If you've found any issue or bug, can you report that specifically? Maybe we can tackle that with a specific test instead of creating a really big build matrix on Travis...

Also, you shouldn't add PHPUnit 6 to the matrix: I already know that we aren't compatible due to #74. I will work on that next month, it needs a lot of rewrite to work around that.

**Comment by sergeyz** [comment]
> Why are you adding all those version tests?

To check that 5.1 works in a same way.

> PHPUnit follows semantic versioning, so a minor version shouldn't break the compatibility.

It isn't, difference in warnings

> Maybe we can tackle that with a specific test instead of creating a really big build matrix on Travis...

I think it's not a huge issue right now. We can exclude a lot and it will decrease once PhpUnit 4 support will be removed

> Also, you shouldn't add PHPUnit 6 to the matrix: I already know that we aren't compatible due to #74. I will work on that next month, it needs a lot of rewrite to work around that.

Yep already saw that. My goal was to check that we don't use deprecated methods. We do actually

**Comment by Jean85** [comment]
I have to use deprecated methods to be cross compatible between PHPUnit 4 and 5. I will obviously drop them as soon as I will drop PHPUnit 4 (see 1.0 milestone). 

I will check on the Travis failures of this PR to see if there are other issues to tackle.

**Comment by Jean85** [comment]
Ok so the only fails, apart from PHPUnit 6, are 5.0 and 5.1. The issue is in PHPUnit itself, that changed its behavior: warnings went from failures to success with message. PHPUnit code is ok, since it shouldn't alter PHPUnit's underlying behavior, but we should fix at least the test.

**Comment by Jean85** [comment]
I will close this. Thanks for bringing it to my attention, but I will fix this later, when I will drop support to PHPUnit 4.x, due to #54; at that point, the `--prefer-lowest` element of the matrix will bring this up.

I would like to avoid such a big (and thus slow) build matrix.

**Pull request closed without merging**
