### PR TITLE
[ISSUE 14] Load XML config with default name

### PR DESCRIPTION
**Pull request by taueres**
This commit fixes issue https://github.com/facile-it/paraunit/issues/14
This PR also adds the shortcut `-c` to the `--configuration` option.

### CODE REVIEW

**Comment by fntlnz** [comment]
:+1:  LGTM

**Comment by fntlnz** [comment]
I would mention the `-c` shortcut into the readme https://github.com/facile-it/paraunit/blob/master/README.md#optional-parameters

**Comment by Jean85** [comment]
Thanks @taueres !!
The `-c` option is already present in the 0.4 branch. But that's right, we need to mention it in the readme, maybe stating that it now behaves like PHPUnit.

If you add that to the readme, and document this changes in the changelog, we can merge this PR ;) Thanks again!

**Comment by ranpafin** [comment]
Good job @taueres :+1: I like the idea of PHPUnitConfigFile being a ValueObject. 

Also, consider we're already using the symfony config component so we can make use of the FileLocator without further dependency.

I think this could be a perfect use case.  From the cookbook:

> The locator receives a collection of locations where it should look for files. The first argument of locate() is the name of the file to look for.

**Comment by taueres** [comment]
@ranpafin Thank you for improving this PR!

**Pull request merged**
